name: DevOps

on:
  push:
    branches: [ main ]
    paths:
      - src/**
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint con flake 8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
  
  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - uses: actions/checkout@v2
          
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/galeria:latest

  aws:
    name: Deploy image to aws
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOSTNAME }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATEKEY }}
        port: 22  # ${{ secrets.PORT }} 
        script: |
            sleep 60
            docker stop web && docker rm web
            docker rmi tropic71/galeria
            docker run -d -p 80:5000 --name web tropic71/galeria:latest

  check:  
    name: checkfor status 200
    runs-on: ubuntu-latest
    needs: aws
    steps:
      - uses: actions/checkout@v2
      - id: text
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "http://${{ secrets.AWS_HOSTNAME }}"
          scan-for-text: "Hello from Flask App"

